/* fetch top n salaries - using rownum */
SELECT * FROM (select DISTINCT SALARY from HR.EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM <= 5;

/* fetch top n salaries - using FETCH FIRST n ROWS */
SELECT DISTINCT SALARY FROM HR.EMPLOYEES ORDER BY SALARY DESC
    FETCH FIRST 5 ROWS ONLY;

/* nth highest salary - using rownum */
SELECT MIN(SALARY) FROM (select DISTINCT SALARY from HR.EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM <= 5;

/* nth highest salary - using OFFSET & FETCH NEXT n ROWS */
SELECT DISTINCT SALARY FROM HR.EMPLOYEES ORDER BY SALARY DESC
    OFFSET 4 ROWS
    FETCH NEXT 1 ROWS ONLY;
    

/* 2nd highest salary */
SELECT MAX(SALARY) FROM HR.EMPLOYEES WHERE SALARY < (SELECT MAX(SALARY) FROM HR.EMPLOYEES);
